import { RegisterPetForm } from "@/interfaces/form";

export const defaultPet: RegisterPetForm = {
  id: "",
  petName: "",
  species: "",
  breed: "",
  birthDate: "",
  age: 0,
  weight: 0,
  colorMarkings: "",
  photo: "",
  requireMedicalInfo: false,
  showAllergies: false,
  allergies: [],
  showMedications: false,
  medications: [],
  showConditions: false,
  conditions: [],
  showVaccinations: false,
  vaccinations: [],
  requireVeterinaryInfo: false,
  veterinaryName: "",
  veterinaryPhone: "",
  veterinaryAddress: "",
  ownerName: "",
  countryCode: "",
  phoneNumber: "",
  email: "",
  address: "",
  requestTag: false,
  tagType: "",
  activate: false,
  disabled: false,
};
